- hosts: all
  become: true
  handlers:
    - name: Reload APT cache
      apt: update_cache=yes
  tasks:
    - name: Download key for the NodeSource repository
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

    - name: Ensure apt-transport-https is installed
      apt: name=apt-transport-https state=present

    - name: Delete the NodeSource repository for 4.x
      apt_repository: repo="deb https://deb.nodesource.com/node_4.x jessie main" state=absent
      notify: Reload APT cache

    - name: Delete the NodeSource repository source for 4.x
      apt_repository: repo="deb-src https://deb.nodesource.com/node_4.x jessie main" state=absent
      notify: Reload APT cache

    - name: Add the NodeSource repository for 6.x
      apt_repository: repo="deb https://deb.nodesource.com/node_6.x jessie main" state=present
      notify: Reload APT cache

    - name: Add the NodeSource repository source 6.x
      apt_repository: repo="deb-src https://deb.nodesource.com/node_6.x jessie main" state=present
      notify: Reload APT cache


- hosts: all
  become: true
  tasks:
    - name: Install NodeJS
      apt: name=nodejs state=latest

    - name: Ensure basic NodeJS tools are available
      npm: name={{item}} global=yes state=latest
      with_items:
        - nodemon
        - gulp
        - grunt


- hosts: all
  tasks:
    - name: Clone tern repository into ~/.tern
      git: dest="~/.tern" update=no repo="https://github.com/ternjs/tern.git"

    - name: Install tern
      npm: path="~/.tern/"
