- hosts: all
  sudo: true
  tasks:
    - name: Ensure that SBCL is available
      apt: name={{item}} state=present
      with_items:
        - sbcl
        - sbcl-source

    - name: Ensure that Scheme is available
      apt: name=racket state=present
