
- hosts: all
  sudo: true
  tasks:
    - name: Ensure basic command line tools are available
      apt: name={{item}} state=present
      with_items:
        - htop
        - screen
        - curl

- hosts: all
  sudo: true
  tasks:
    - name: Ensure some more advanced tools are available too
      apt: name={{item}} state=present
      with_items:
        - jq
        - xvfb
        - imagemagick

- hosts: all
  tasks:
    - name: Create additional directory strucuture in the home
      file: path="{{item}}" state=directory
      with_items:
        - ~/bin
        - ~/tmp
        - ~/Projects
