- hosts: all
  sudo: true
  tasks:
    - name: Ensure basic command line tools are available
      apt: name={{item}} state=present
      with_items:
        - htop
        - screen
        - curl
        - tree
        - unzip

- hosts: all
  sudo: true
  tasks:
    - name: Ensure some more advanced tools are available too
      apt: name={{item}} state=present
      with_items:
        - jq
        - xvfb
        - imagemagick


- hosts: all
  tags: personal
  tasks:
    - name: Create additional directory strucuture in the home
      file: path="{{item}}" state=directory
      with_items:
        - ~/bin
        - ~/tmp
        - ~/Projects


- hosts: all
  sudo: true
  handlers:
    - name: Reload APT cache
      apt: update_cache=yes
      
  tasks:
    - name: Install ansible dependencies
      apt: name=python-apt state=present

    - name: Add contrib packages to sources.list
      lineinfile: regexp="^deb .*ftp\.nl\.debian\.org/debian/ jessie main" backup=yes state=present line="deb http://ftp.nl.debian.org/debian/ jessie main contrib non-free" dest=/etc/apt/sources.list
      notify: Reload APT cache

    - name: Add contrib packages to sources.list
      lineinfile: regexp="^deb-src .*ftp\.nl\.debian\.org/debian/ jessie main" backup=yes state=present line="deb-src http://ftp.nl.debian.org/debian/ jessie main contrib non-free" dest=/etc/apt/sources.list
      notify: Reload APT cache
