
- hosts: all
  sudo: true
  handlers:
    - name: Reload APT cache
      apt: update_cache=yes
      
  tasks:
    - name: Install ansible dependencies
      apt: name=python-apt state=present

    - name: Add contrib packages to sources.list
      lineinfile: regexp="^deb .*ftp\.nl\.debian\.org/debian/ jessie main" backup=yes state=present line="deb http://ftp.nl.debian.org/debian/ jessie main contrib non-free" dest=/etc/apt/sources.list
      notify: Reload APT cache

    - name: Add contrib packages to sources.list
      lineinfile: regexp="^deb-src .*ftp\.nl\.debian\.org/debian/ jessie main" backup=yes state=present line="deb-src http://ftp.nl.debian.org/debian/ jessie main contrib non-free" dest=/etc/apt/sources.list
      notify: Reload APT cache


- hosts: all
  sudo: true
  tasks:
    - name: Ensure that Git is installed
      apt: name=git state=present

    - name: Ensure that GNU/Emacs is installed
      apt: name={{item}} state=present
      with_items:
        - emacs24
        - emacs24-el
        - emacs24-common-non-dfsg

- hosts: all
  tasks:
    - name: Configure GNU/Emacs from the dotemacs repository
      git: dest="~/.emacs.d/dotemacs" update=no repo="https://github.com/davazp/dotemacs.git"

- hosts: all
  sudo: true
  tasks:
    - name: Ensure that SBCL is available
      apt: name=sbcl state=present
