- include: development/emacs.yml
- include: development/node.yml
- include: development/lisp.yml
- include: development/lua.yml
- include: development/haskell.yml

- hosts: all
  sudo: true
  tasks:
    - name: Install system programming tools
      apt: name={{item}} state=present
      with_items:
        - ltrace
        - strace
        - linux-tools

- hosts: all
  sudo: true
  tasks:
    - name: Ensure sqlite3 command line tool is installed
      apt: name=sqlite3 state=present

- hosts: all
  tags: personal
  tasks:
    - name: Configure utilities by cloning the dotfiles repository
      git: dest="~/.dotfiles" update=no repo="https://github.com/davazp/dotfiles.git"
