- hosts: all
  sudo: true
  handlers:
    - name: Reload APT cache
      apt: update_cache=yes
  tasks:
    - name: Download and install key for PostgreSQL repository
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

    - name: Add the PostgreSQL repository
      apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main" state=present
      notify: Reload APT cache


- hosts: all
  sudo: true
  tasks:
    - name: Install PostgreSQL 9.5 and tools
      apt: name={{item}} state=present
      with_items:
        - postgresql-9.5
        # used by postgresql related ansible modulesq
        - python-psycopg2

- hosts: all
  sudo: true
  sudo_user: postgres
  tasks:
    - name: Add my user as an admin to PostgreSQL
      # TODO: Get the username before sudoing to postgresql instead
      postgresql_user: name=davazp role_attr_flags=SUPERUSER
